module.exports = {
  securedPath: '/IA/Asylum',
  createAppealHomeOfficeDecision: '/IA/Asylum/create-appeal/home-office-decision',
  createAppealBasicDetails: '/IA/Asylum/create-appeal/basic-details',
  createAppealNationality: '/IA/Asylum/create-appeal/nationality',
  createAppealAddress: '/IA/Asylum/create-appeal/address',
  createAppealAppealReason: '/IA/Asylum/create-appeal/appeal-reason',
  createAppealGroundsOfAppeal: '/IA/Asylum/create-appeal/grounds-of-appeal',
  createAppealNewMatters: '/IA/Asylum/create-appeal/new-matters',
  createAppealHasOtherAppeals: '/IA/Asylum/create-appeal/has-other-appeals',
  createAppealOtherAppeals: '/IA/Asylum/create-appeal/other-appeals',
  createAppealReferenceNumber: '/IA/Asylum/create-appeal/reference-number',
  createAppealOutOfTime: '/IA/Asylum/create-appeal/out-of-time',
  createAppealCheckAnswers: '/IA/Asylum/create-appeal/check-answers',
  createAppeal: '/IA/Asylum/create-appeal',
  groundsOfAppeal: '/IA/Asylum/:caseId(\\d+)/grounds-of-appeal',
  legalArgument: '/IA/Asylum/:caseId(\\d+)/legal-argument',
  submitCase: '/IA/Asylum/:caseId(\\d+)/submit-case',
  health: '/health',
  robots: '/robots.txt'
};
